version: '2'
services:
    myapplication-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/myapplication/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=myapplication
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
